# Adapted from https://github.com/JamesIves/github-pages-deploy-action
name: Build and Deploy Scroll
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          rm .gitignore
          npm install .
          node ./scroll.js list | node ./scroll.js build
          cd blog
          echo "Installing packages for markups demo in blog."
          mkdir node_modules
          npm install marked textile-js ya-bbcode
          echo "Building blog."
          ../scroll.js build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: wws # The branch the action should deploy to.
          folder: .
